config/routes.rb
Rails.application.routes.draw do
  root to: 'meals#show'

  get '/login', to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  post '/logout', to: 'sessions#delete'

  get '/report', to: 'report#show', as: :report
  get '/admin', to: 'admin#show', as: :admin

  namespace :api do
    get '/meals' => 'meals#index'
    get '/bills' => 'bills#index'
    get '/residents' => 'residents#index'
    get '/units' => 'units#index'
    get '/report' => 'report#show'
  end

  resources :residents, except: [:create, :update]
  post '/residents/new' => 'residents#create'
  patch '/residents/:id/edit' => 'residents#update'

  resources :bills, except: [:create, :update]
  post '/bills/new' => 'bills#create'
  patch '/bills/:id/edit' => 'bills#update'

  resources :units, except: [:create, :update]
  post '/units/new' => 'units#create'
  patch '/units/:id/edit' => 'units#udpate'

  resources :meals, except: [:create, :update]
  post '/meals/new' => 'meals#create'
  patch '/meals/:id/edit' => 'meals#update'

  resources :communities, except: [:create, :update]
  post '/communities/new' => 'communities#create'
  patch '/communities/:id/edit' => 'communities#update'

  resources :reconciliations, only: [:create]
end

app/models/resident.rb
# == Schema Information
#
# Table name: residents
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  multiplier      :integer          default(2), not null
#  unit_id         :integer
#  bill_costs      :integer          default(0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  admin           :boolean          default(FALSE), not null
#
# Indexes
#
#  index_residents_on_name             (name) UNIQUE
#  index_residents_on_password_digest  (password_digest) UNIQUE
#  index_residents_on_unit_id          (unit_id)
#
# Foreign Keys
#
#  fk_rails_...  (unit_id => units.id)
#

class Resident < ApplicationRecord
  has_secure_password validations: false

  belongs_to :unit
  has_many :bills, dependent: :destroy
  has_many :meal_residents, dependent: :destroy
  has_many :meals, through: :meal_residents
  has_many :guests, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :password_digest, presence: true, if: "admin"
  validates :multiplier, numericality: { only_integer: true }


  # DERIVED DATA
  def bill_reimbursements
    return 0 if Meal.unreconciled.count == 0
    bills.joins(:meal).where({:meals => {:reconciliation_id =>  nil}}).reduce(0) { |sum, bill| sum + bill.reimburseable_amount }
  end

  def meal_resident_costs
    return 0 if Meal.unreconciled.count == 0
    meal_residents.joins(:meal).where({:meals => {:reconciliation_id =>  nil}}).reduce(0) { |sum, meal_resident| sum + meal_resident.cost }
  end

  def guest_costs
    return 0 if Meal.unreconciled.count == 0
    guests.joins(:meal).where({:meals => {:reconciliation_id =>  nil}}).reduce(0) { |sum, guest| sum + guest.cost }
  end

  def balance
    return 0 if Meal.unreconciled.count == 0
    bill_reimbursements - meal_resident_costs - guest_costs
  end

  def meals_attended
    return 0 if Meal.unreconciled.count == 0
    meal_residents.joins(:meal).where({:meals => {:reconciliation_id =>  nil}}).count
  end
end

app/controllers/api/residents_controller.rb
module Api
  class ResidentsController < ApplicationController
    #before_action :signed_in?

    def index
      residents = Resident.order(:name).includes({ :bills => :meal }, { :meal_residents => :meal }, { :guests => :meal })
      render json: residents
    end
  end
end

app/controllers/residents_controller.rb
# == Schema Information
# Schema version: 20160309185245
#
# Table name: residents
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  multiplier :integer          default(2), not null
#  unit_id    :integer
#  bill_costs :integer          default(0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  vegetarian :boolean          default(FALSE), not null
#
# Indexes
#
#  index_residents_on_name     (name) UNIQUE
#  index_residents_on_unit_id  (unit_id)
#
# Foreign Keys
#
#  fk_rails_8ddf6a82d6  (unit_id => units.id)
#

class ResidentsController < ApplicationController
  before_action :signed_in?
  before_action :admin?, except: [:index, :show]
  before_action :set_resident, only: [:show, :update, :destroy]

  # GET /residents
  def index
    @residents = Resident.order("units.name").includes(:unit).all.page(params[:page])
  end

  # GET /residents/1
  def show
  end

  # GET /residents/new
  def new
    @resident = Resident.new
  end

  # GET /residents/1/edit
  def edit
    @resident = Resident.find(params[:id])
  end

  # POST /residents
  def create
    @resident = Resident.new(resident_params)
    if @resident.save
      redirect_to residents_url, notice: 'Resident was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /residents/1
  def update
    if @resident.update(resident_params)
      redirect_to residents_url, notice: 'Resident was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /residents/1
  def destroy
    if @resident.destroy
      redirect_to residents_url, notice: 'Resident was successfully destroyed.'
    else
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resident
      @resident = Resident.includes({ :bills => :meal }, { :meal_residents => :meal }, { :guests => :meal }, :unit).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resident_params
      params.require(:resident).permit(:name, :multiplier, :unit_id)
    end
end

app/views/residents/_form.html.erb
<%= simple_form_for @resident, url: { action: lambda { @resident.new_record? ? "create" : "update" }.call }, html: { class: "form-horizontal resident" } do |f| %>

  <!-- Errors -->
  <% if @resident.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being <%= @resident.new_record? ? "created" : "updated" %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @resident.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!-- Attributes -->
  <div class="form-group">
    <%= f.label :name, required: false, class: "control-label col-xs-2" %>
    <div class="col-xs-10">
      <%= f.text_field :name, class: "form-control", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :multiplier, class: "control-label col-xs-2" %>
    <div class="col-xs-10">
      <%= f.text_field :multiplier, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-4">
      <%= f.association :unit, collection: Unit.order(:name), class: "form-control" %>
    </div>
  </div>

  <!-- Submit / Cancel buttons -->
  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
      <%= f.submit nil, class: "btn btn-primary" %>
      <%= link_to('Cancel', residents_path, class: "btn btn-default") %>
    </div>
  </div>

<% end %>

app/views/residents/_resident.html.erb
<tr>
  <td><%= link_to resident.id, resident_path(resident), class: 'id-link' %></td>
  <td><%= resident.name %></td>
  <td><%= category_helper(resident.multiplier) %></td>
  <td><%= resident.unit&.name %></td>
  <td>
    <%= link_to('Edit',
                edit_resident_path(resident),
                class: "btn btn-default btn-xs") if @admin %>
    <%= link_to('Delete',
                resident_path(resident),
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: "btn btn-xs btn-danger") if @admin %>
  </td>
</tr>

app/views/residents/edit.html.erb
<div class="page-header">
  <h1>Edit Resident</h1>
</div>

<%= render partial: 'form' %>

app/views/residents/index.html.erb
<div class="page-header">
  <h1>Residents</h1>
</div>

<%= link_to('New', new_resident_path, class: "btn btn-primary") if @admin %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Category</th>
      <th>Unit</th>
      <th><%= 'Actions' if @admin %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @residents %>
  </tbody>
</table>

<%= paginate @residents %>

app/views/residents/new.html.erb
<div class="page-header">
  <h1>New Resident</h1>
</div>

<%= render partial: 'form' %>

app/views/residents/show.html.erb
<div class="page-header">
  <h1>Resident</h1>
</div>

  <!-- Errors -->
  <% if @resident.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being deleted:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @resident.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<!-- Attributes -->
<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @resident.name %></dd>

  <dt><strong>Category:</strong></dt>
  <dd><%= category_helper(@resident.multiplier) %></dd>

  <dt><strong>Unit:</strong></dt>
  <dd><%= @resident.unit&.name %></dd>

  <dt><strong>Bill Costs:</strong></dt>
  <dd><%= number_to_currency(@resident.bill_costs/100.to_f) %></dd>

  <dt><strong>Bill Reimbursements:</strong></dt>
  <dd><%= number_to_currency(@resident.bill_reimbursements/100.to_f) %></dd>

  <dt><strong>Meal Resident Costs:</strong></dt>
  <dd><%= number_to_currency(@resident.meal_resident_costs/100.to_f) %></dd>

  <dt><strong>Guest_costs:</strong></dt>
  <dd><%= number_to_currency(@resident.guest_costs/100.to_f) %></dd>

  <dt><strong>Balance:</strong></dt>
  <dd><%= number_to_currency(@resident.balance/100.to_f) %></dd>
</dl>

<!-- Back / Edit / Delete buttons -->
<%= link_to('Back', residents_path, class: "btn btn-default") %>
<%= link_to('Edit', edit_resident_path(@resident), class: "btn btn-default") if @admin %>
<%= link_to('Delete',
            resident_path(@resident),
            method: 'delete',
            data: { confirm: 'Are you sure?' },
            class: "btn btn-danger") if @admin %>