config/routes.rb
Rails.application.routes.draw do
  root to: 'meals#show'

  get '/login', to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  post '/logout', to: 'sessions#delete'

  get '/report', to: 'report#show', as: :report
  get '/admin', to: 'admin#show', as: :admin

  namespace :api do
    get '/meals' => 'meals#index'
    get '/bills' => 'bills#index'
    get '/residents' => 'residents#index'
    get '/units' => 'units#index'
    get '/report' => 'report#show'
  end

  resources :residents, except: [:create, :update]
  post '/residents/new' => 'residents#create'
  patch '/residents/:id/edit' => 'residents#update'

  resources :bills, except: [:create, :update]
  post '/bills/new' => 'bills#create'
  patch '/bills/:id/edit' => 'bills#update'

  resources :units, except: [:create, :update]
  post '/units/new' => 'units#create'
  patch '/units/:id/edit' => 'units#udpate'

  resources :meals, except: [:create, :update]
  post '/meals/new' => 'meals#create'
  patch '/meals/:id/edit' => 'meals#update'

  resources :communities, except: [:create, :update]
  post '/communities/new' => 'communities#create'
  patch '/communities/:id/edit' => 'communities#update'

  resources :reconciliations, only: [:create]
end

app/models/unit.rb
# == Schema Information
# Schema version: 20160202150722
#
# Table name: units
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_units_on_name  (name) UNIQUE
#

class Unit < ApplicationRecord
  has_many :residents, dependent: :destroy
  validates :name, uniqueness: true, presence: true

  # DERIVED DATA
  def balance
    return 0 if Meal.unreconciled.count == 0
    residents.reduce(0) { |sum, resident| sum + resident.balance }
  end

  def meals_cooked
    return 0 if Meal.unreconciled.count == 0
    residents.reduce(0) { |sum, resident| sum + resident.bills.joins(:meal).where({:meals => {:reconciliation_id =>  nil}}).count }
  end
end

app/controllers/api/units_controller.rb
module Api
  class UnitsController < ApplicationController
    #before_action :signed_in?

    def index
      units = Unit.order(:name).includes({ :residents => { :bills => :meal }}, { :residents => { :meal_residents => :meal }}, { :residents => { :guests => :meal }})
      render json: units
    end
  end
end

app/controllers/units_controller.rb
# == Schema Information
# Schema version: 20160202150722
#
# Table name: units
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_units_on_name  (name) UNIQUE
#

class UnitsController < ApplicationController
  before_action :signed_in?
  before_action :admin?, except: [:index]
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  def index
    @units = Unit.order(:name).page(params[:page])
  end

  # GET /units/1
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      redirect_to units_url, notice: 'Unit was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /units/1
  def update
    if @unit.update(unit_params)
      redirect_to units_url, notice: 'Unit was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /units/1
  def destroy
    if @unit.destroy
      redirect_to units_url, notice: 'Unit was successfully destroyed.'
    else
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/views/units/_form.html.erb
<%= simple_form_for @unit, url: { action: lambda { @unit.new_record? ? "create" : "update" }.call }, html: { class: "form-horizontal unit" } do |f| %>

  <!-- Errors -->
  <% if @unit.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being <%= @unit.new_record? ? 'created' : 'updated' %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @unit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!-- Name -->
  <div class="form-group">
    <%= f.label :name, required: false, class: "control-label col-xs-2" %>
    <div class="col-xs-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <!-- Submit / Cancel Buttons -->
  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
      <%= f.submit nil, class: "btn btn-primary" %>
      <%= link_to('Cancel', units_path, class: "btn btn-default") %>
    </div>
  </div>

<% end %>

app/views/units/edit.html.erb
<div class="page-header">
  <h1>Edit Unit</h1>
</div>

<%= render partial: 'form' %>

app/views/units/index.html.erb
<div class="page-header">
  <h1>Units</h1>
</div>

<%= link_to('New', new_unit_path, class: "btn btn-primary") if @admin %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th><%= 'Actions' if @admin %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td>
          <%= link_to('Edit',
                      edit_unit_path(unit),
                      class: "btn btn-default btn-xs") if @admin %>
          <%= link_to('Delete',
                      unit_path(unit),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "btn btn-xs btn-danger") if @admin %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @units %>

app/views/units/new.html.erb
<div class="page-header">
  <h1>New Unit</h1>
</div>

<%= render partial: 'form' %>

app/views/units/show.html.erb
<div class="page-header">
  <h1>Unit</h1>
</div>

<!-- Errors -->
<% if @unit.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being deleted:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<!-- Attributes -->
<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @unit.name %></dd>
</dl>

<!-- Back / Edit / Delete buttons -->
<%= link_to('Back', units_path, class: "btn btn-default") %>
<%= link_to('Edit', edit_unit_path(@unit), class: "btn btn-default") if @admin %>
<%= link_to('Delete',
            unit_path(@unit),
            method: 'delete',
            data: { confirm: 'Are you sure?' },
            class: "btn btn-danger") if @admin %>