config/routes.rb
Rails.application.routes.draw do
  root to: 'meals#show'

  get '/login', to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  post '/logout', to: 'sessions#delete'

  get '/report', to: 'report#show', as: :report
  get '/admin', to: 'admin#show', as: :admin

  namespace :api do
    get '/meals' => 'meals#index'
    get '/bills' => 'bills#index'
    get '/residents' => 'residents#index'
    get '/units' => 'units#index'
    get '/report' => 'report#show'
  end

  resources :residents, except: [:create, :update]
  post '/residents/new' => 'residents#create'
  patch '/residents/:id/edit' => 'residents#update'

  resources :bills, except: [:create, :update]
  post '/bills/new' => 'bills#create'
  patch '/bills/:id/edit' => 'bills#update'

  resources :units, except: [:create, :update]
  post '/units/new' => 'units#create'
  patch '/units/:id/edit' => 'units#udpate'

  resources :meals, except: [:create, :update]
  post '/meals/new' => 'meals#create'
  patch '/meals/:id/edit' => 'meals#update'

  resources :communities, except: [:create, :update]
  post '/communities/new' => 'communities#create'
  patch '/communities/:id/edit' => 'communities#update'

  resources :reconciliations, only: [:create]
end

app/models/community.rb
# == Schema Information
#
# Table name: communities
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  cap             :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  rotation_length :integer
#
# Indexes
#
#  index_communities_on_name  (name) UNIQUE
#

class Community < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validate :only_one, on: :create

  def cap
    read_attribute(:cap) || Float::INFINITY
  end

  private
    def only_one
      errors[:base] << 'Only one community permitted.' if Community.count > 0
    end
end

app/controllers/communities_controller.rb
# == Schema Information
# Schema version: 20160324173111
#
# Table name: communities
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  cap             :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  rotation_length :integer
#  time_zone       :string           default("UTC"), not null
#
# Indexes
#
#  index_communities_on_name  (name) UNIQUE
#

class CommunitiesController < ApplicationController
  before_action :signed_in?
  before_action :admin?, except: [:index]
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  def index
    @communities = Community.all
  end

  # GET /communities/1
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities/new
  def create
    @community = Community.new(community_params)
    if @community.save
      redirect_to communities_url, notice: 'Community was successfully created.'
    else
      render :new
    end
  end

  # PATCH /communities/1/edit
  def update
    if @community.update(community_params)
      redirect_to communities_url, notice: 'Community was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /communities/1
  def destroy
    if @community.destroy
      redirect_to communities_url, notice: 'Community was successfully destroyed.'
    else
      render :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :cap, :rotation_length)
    end
end

app/views/communities/_form.html.erb
<%= simple_form_for @community, url: { action: lambda { @community.new_record? ? "create" : "update" }.call }, html: { class: "form-horizontal community" } do |f| %>

  <!-- Errors -->
  <% if @community.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@community.errors.count, "error") %> prohibited this community from being <%= @community.new_record? ? 'created' : 'updated' %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @community.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!-- Name -->
  <div class="form-group">
    <%= f.label :name, required: false, class: "control-label col-xs-3" %>
    <div class="col-xs-7">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <!-- Cap -->
  <div class="form-group">
    <%= f.label :cap, class: "control-label col-xs-3" %>
    <div class="col-xs-7">
      <%= f.number_field :cap, class: "form-control", placeholder: 'Cents per person unit' %>
    </div>
  </div>

  <!-- Rotation Length -->
  <div class="form-group">
    <%= f.label :rotation_length, class: "control-label col-xs-3" %>
    <div class="col-xs-7">
      <%= f.number_field :rotation_length, class: "form-control", placeholder: 'How many meals are in a rotation?' %>
    </div>
  </div>

  <!-- Submit / Cancel buttons -->
  <div class="form-group">
    <div class="col-xs-offset-3 col-xs-9">
      <%= f.submit nil, class: "btn btn-primary" %>
      <%= link_to 'Cancel', communities_path, class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/communities/edit.html.erb
<div class="page-header">
  <h1>Edit Community</h1>
</div>

<%= render partial: 'form' %>

app/views/communities/index.html.erb
<div class="page-header">
  <h1>Community</h1>
</div>

<%= link_to('New', new_community_path, class: "btn btn-primary") if @admin %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Cap</th>
      <th>Rotation</th>
      <th><%= 'Actions' if @admin %></th>
    </tr>
  </thead>
  <tbody>
    <% @communities.each do |community| %>
      <tr>
        <td><%= community.name %></td>
        <td><%= number_to_currency((community.cap)/100.to_f) %>/person unit</td>
        <td><%= format_rotation_length(community.rotation_length) %></td>
        <td>
          <%= link_to('Edit', edit_community_path(community), class: "btn btn-default btn-xs") if @admin %>

          <%= link_to('Delete',
                      community_path(community),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "btn btn-xs btn-danger") if @admin %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/communities/new.html.erb
<div class="page-header">
  <h1>New Community</h1>
</div>

<%= render partial: 'form' %>

app/views/communities/show.html.erb
<div class="page-header">
  <h1>Community</h1>
</div>

<!-- Errors -->
<% if @community.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@community.errors.count, "error") %> prohibited this community from being deleted:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<!-- Attributes -->
<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @community.name %></dd>

  <dt><strong>Cap:</strong></dt>
  <dd><%= @community.cap %></dd>

  <dt><strong>Rotation:</strong></dt>
  <dd><%= @community.rotation_length %> meals</dd>
</dl>

<!-- Back / Edit / Delete buttons -->
<%= link_to('Back', communities_path, class: "btn btn-default") %>
<%= link_to('Edit', edit_community_path(@community), class: "btn btn-default") if @admin %>
<%= link_to('Delete',
            community_path(@community),
            method: 'delete',
            data: { confirm: 'Are you sure?' },
            class: "btn btn-danger") if @admin %>