config/routes.rb
Rails.application.routes.draw do
  root to: 'meals#show'

  get '/login', to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  post '/logout', to: 'sessions#delete'

  get '/report', to: 'report#show', as: :report
  get '/admin', to: 'admin#show', as: :admin

  namespace :api do
    get '/meals' => 'meals#index'
    get '/bills' => 'bills#index'
    get '/residents' => 'residents#index'
    get '/units' => 'units#index'
    get '/report' => 'report#show'
  end

  resources :residents, except: [:create, :update]
  post '/residents/new' => 'residents#create'
  patch '/residents/:id/edit' => 'residents#update'

  resources :bills, except: [:create, :update]
  post '/bills/new' => 'bills#create'
  patch '/bills/:id/edit' => 'bills#update'

  resources :units, except: [:create, :update]
  post '/units/new' => 'units#create'
  patch '/units/:id/edit' => 'units#udpate'

  resources :meals, except: [:create, :update]
  post '/meals/new' => 'meals#create'
  patch '/meals/:id/edit' => 'meals#update'

  resources :communities, except: [:create, :update]
  post '/communities/new' => 'communities#create'
  patch '/communities/:id/edit' => 'communities#update'

  resources :reconciliations, only: [:create]
end

app/views/layouts/_flash.html.erb
<!-- Notice -->
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>

<!-- Error -->
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<!-- Header -->
<div class="page-header">
  <%= link_to('Community', communities_path, class: "btn btn-info btn-xs dark") if @admin %>
  <%= link_to('Meal Forms', meals_path(q: 'current'), class: "btn btn-info btn-xs dark") %>
  <%= link_to('Bills', bills_path, class: "btn btn-info btn-xs dark") if @admin %>
  <%= link_to('Residents', residents_path, class: "btn btn-info btn-xs dark") if @admin %>
  <%= link_to('Units', units_path, class: "btn btn-info btn-xs dark") if @admin %>
  <%= link_to('Balance Report', report_path, class: "btn btn-info btn-xs dark") %>
  <%= link_to('Admin', admin_path, class: "btn btn-info btn-xs dark") if @admin %>
  <%= link_to "Log Out #{resident_name_helper(Resident.find(@resident_id).name)} #{' (admin)' if @admin}", logout_path, method: :post, class: "btn btn-default btn-xs pull-right" if @signed_in %>
  <% if params[:controller] != 'sessions' %>
    <%= link_to "Log In", login_path, class: "btn btn-default btn-xs pull-right" unless @signed_in %>
  <% end %>
</div>

app/views/layouts/_notice.html.erb
<!-- Notice -->
<% if notice %>
  <button type="button">
    <span>&times;</span>
  </button>
  <%= notice %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Comeals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/notie/dist/notie.min.css">
  </head>

  <body>
    <div class="container" style="min-width: 1800px; max-width: 3600px">
      <%= render partial: 'layouts/flash' %>
      <%= render partial: 'layouts/header' %>

      <div class="row">
        <div id="calendar" class="col-xs-6"></div>
        <div class="col-xs-6">
          <%= yield %>
        </div>
      </div>

    </div>
    <%= javascript_include_tag 'calendar' %>
    <%= javascript_include_tag 'common' %>
    <script src="https://unpkg.com/notie"></script>
  </body>
</html>

app/views/layouts/calendar.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Comeals - Calendar</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'calendar', media: 'all' %>
    <%= javascript_include_tag 'calendar_manifest' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= javascript_include_tag 'init_qtip' %>
  </body>
</html>